Fixed issue #1
opsdroid/connector-github pull request #2
Opened 2017-10-04 00:58 UTC by CalderWhite

In theory, I should have fixed issue #1 , however I was unable to test the code on my own machine. @jacobtomlinson , if you could test that the code works that would be great!

2017-10-04 06:55 UTC, jacobtomlinson commented
Hey thanks for this!

This project is already using `aiohttp` to make asynchronous http requests, so also including `requests` is a bit of a waste. It would also cause the function to be blocking as requests doesn't work with `asyncio` yet.

Also could you let me know why you were unable to test locally? This could be something which needs fixing in the documentation.

2017-10-04 20:54 UTC, CalderWhite commented
Okay, finally got to the bottom of my issues. First and foremost, development on ubuntu 14.04 is tricky, since the default installation of python is python3.4, which is not compatible with opsdroid. Because of this, I had to go through the process of upgrading python and pip. Except I ran into a bunch of issues with upgrading pip. Long story short, I moved to windows.     
    
On windows I'm running an anaconda python 3.6.2, and everything worked smoothly. The only issue is I didn't fully understand the infrastructure of `opsdroid` and how it works, so I foolishly edited my code inside my git repository, instead of at `C:\%HOMEPATH%\.opsdroid\modules\opsdroid-modules\connector\github`. However, there is no "developement" section of the `README.md` or the [documentation](http://opsdroid.readthedocs.io/en/stable/). Perhaps that is another issue?    

After a couple of hours of sorting all this out, I am just beginning to test my bug fix. I will comment back soon, when I have either the results, or a new commit with a new fix.

2017-10-04 22:21 UTC, jacobtomlinson commented
All good points! There is a contributing section of the docs but perhaps a developers section would be useful too 

Virtual environments are definitely your friend here, although as you said upgrading Python or installing alternate versions can be a pain. 

Keep me up to date with how you get on!

2017-10-04 23:22 UTC, CalderWhite commented
@jacobtomlinson tested and fixed!

2017-10-10 00:31 UTC, CalderWhite commented
Hey, I know maintaining open source projects is a large job @jacobtomlinson , but would you mind either merging or giving feed back on my updated PR?

Thanks!

2017-10-16 10:43 UTC, jacobtomlinson commented
Sorry I've been away on holiday. I should be more timely in my reviews now.

2017-10-16 10:49 UTC, jacobtomlinson reviewed
This is a fantastic PR. I've added some rather picky comments about PEP8 stuff. But you're code is really good!

2017-10-16 10:49 UTC, jacobtomlinson commented on __init__.py
> +import aiohttp, asyncio
Please break the imports onto two lines. I appreciate this is a personal preference but it would bring it in line with the rest of the project.

2017-10-16 10:49 UTC, jacobtomlinson commented on __init__.py
> +    def _getSite(url):
Please switch this method to the [PEP8 underscore naming convention](https://www.python.org/dev/peps/pep-0008/#function-names)

2017-10-16 10:49 UTC, jacobtomlinson commented on __init__.py
> +        response = yield from aiohttp.request('GET', url)
In python 3.5 `yield from` has been replaced with `await` please update.

2017-10-16 10:49 UTC, jacobtomlinson commented on __init__.py
> +        raw_json = loop.run_until_complete(ConnectorGitHub._getSite('https://api.github.com/user?access_token='+self.github_token))
This line is a little long. Please break it up a little. And don't forget your [PEP8 spacing](https://www.python.org/dev/peps/pep-0008/#whitespace-in-expressions-and-statements) :).

2017-10-16 10:49 UTC, jacobtomlinson commented on __init__.py
> +        botData = json.loads(raw_json)
PEP8 variable naming convention has underscored not camel case.

2017-10-16 21:47 UTC, CalderWhite commented
Attempted to fix style issues!

2017-10-17 07:03 UTC, jacobtomlinson reviewed
Nice one! Just a couple more things.

2017-10-17 07:03 UTC, jacobtomlinson commented on __init__.py
> +    @staticmethod
Could you move this method to after the `__init__`.

2017-10-17 07:03 UTC, jacobtomlinson commented on __init__.py
> +        loop = asyncio.get_event_loop()
You can use `self.opsdroid. eventloop` instead of getting it yourself.

2017-10-17 07:37 UTC, jacobtomlinson commented on __init__.py
> +        loop = asyncio.get_event_loop()
Actually I see you're running this in the `__init__` so that wont be populated yet. Can you move the whole section into the `connect` method

2017-10-17 07:38 UTC, jacobtomlinson commented on __init__.py
> +        print(message.user,self.github_username)
Can you fix the whitespace here after the comma.

2017-10-18 10:01 UTC, jacobtomlinson commented
Hey. I'm eager to get this merged. Are you able to make the last couple of changes?

2017-10-18 19:57 UTC, CalderWhite commented
Updated.

2017-10-20 07:15 UTC, jacobtomlinson requested changes
You're making life hard for yourself with the asyncio stuff 😄 . Hopefully these suggestions will help.

2017-10-20 07:15 UTC, jacobtomlinson commented on __init__.py
> +    def get_site(url):
This should be `async def get_site(url)`.

2017-10-20 07:15 UTC, jacobtomlinson commented on __init__.py
> +        raw_json = loop.run_until_complete(
One you make `get_site` a coroutine you do not need to mess around with the loop. You can simply `await self.get_site('https://api.github.com/user?access_token=' + self.github_token`.

Also `GITHUB_API_URL` is defined at the top, you might want to make use of it.

2017-10-21 07:48 UTC, jacobtomlinson requested changes
This is what I was after, however there are syntax errors. Have you tested this?

2017-10-21 07:48 UTC, jacobtomlinson commented on __init__.py
> +        loop = self.opsdroid.eventloop
This is no longer needed.

2017-10-21 07:48 UTC, jacobtomlinson commented on __init__.py
> +        raw_json = awaitself.get_site(
You need a space after await.

2017-10-21 07:48 UTC, jacobtomlinson commented on __init__.py
> +                GITHUB_API_URL+'/user?access_token='+self.github_token
Please add spaces either side of the `+` symbol.

2017-10-22 09:10 UTC, jacobtomlinson commented
There's been quite a bit of back and forth on this PR and it's mostly been stylistic changes. In order to speed things up I've forked your PR in #3 and added a final few changes myself. I'm going to close this one and merge #3, but don't worry your commits are still going in and this PR still counts towards Hacktoberfest.

2017-10-22 09:10 UTC, closed without merging